version: "3.3"

services:
  az-util-devel:
    image: golang:latest
    container_name: az-util-devel-${USER}
    network_mode: "host"
    working_dir: /root/go/src/az-util
    volumes:
      - "../:/root/go/src/az-util"
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/go/bin
    entrypoint:
      - bash
      - -c
      - make ${TARGET:-dev} MAIN_PKG=${MAIN_PKG:-az-util} ARG='${ARG}'